1. numpy 배열
1. numpy 배열의 생성과 변형
1. numpy 배열의 연산
1. 기술통계
1. 난수발생과 카운팅

* `Numpy의 핵심은 ndarray이다.`
* `np.array()함수는 list, tuple, array로 부터 ndarrary객체를 생성`
* ndarray는 N-dimensional Array의 약자이다. 즉, `다차원(1,2,...N차원)배열 자료구조를 지원`한다.

In [1]:
import numpy as np

##### 1. numpy 배열

In [4]:
# 1. 1차원배열 만들기
# np.array()함수에 list자료형을 전달하면 ndarray 객체 즉, 배열로 리턴한다.
# ndarray는 list와 유산한 구조처럼보이지만 배열객체와 리스트객체는 많은 차이가 있다.
# 1. list에는 서로 다른 타입의 자료를 저장할 수 있지만 ndarray은 동일 타입의 자료만 저장이 가능
# 2. ndarray는 다차원배열의 수치자료를 연산할 수 있다.
arr1 = np.array([1,2,3,4,5])
print(type(arr1), arr1)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [12]:
# 데이터타입이 틀린경우 강제형변환이 가능하다. 
# 1) 수치자료형은 상위의 데이터타입으로 변환이 된다.
# 2) string 요소가 있을 경우에 수치타입은 전부 str타입으로 강제형변환된다.
arr1 = np.array([1.0, 2, 3, 1.0])  # int -> float
print(type(arr1), arr1)
print()

arr2 = np.array([1.0, 2, 3, '1.0']) # 각요소가 전부 string타입으로 강제형변환
print(type(arr2), arr2)
print(type(arr2[3]), arr2[3])

arr3 = np.array([1.0, 2, 3, '일'])
print(type(arr3), arr3)
print(type(arr3[3]), arr3[3])

<class 'numpy.ndarray'> [1. 2. 3. 1.]

<class 'numpy.ndarray'> ['1.0' '2' '3' '1.0']
<class 'numpy.str_'> 1.0
<class 'numpy.ndarray'> ['1.0' '2' '3' '일']
<class 'numpy.str_'> 일


In [23]:
# 비동차는 지원하지 않는다. 차원이 다를 경우 에러가 발생된다.
# 즉, ndarray의 요소의 차원수는 동일해야 한다.
# 동차(homogeneous), 비동차(inhomogeneous)
list1 = [1,2,3, '4', [5,6]]
print(type(list1), list1)
# arr4 = np.array(list1) # 비동차에러, inhomogeneous part

list2 = [[1,2], [3,4]] # 첫 번쨰 요소와 두 번째 요소 모두 동차(1차원), 
arr4 = np.array(list2)
print(type(arr4), arr4)

<class 'list'> [1, 2, 3, '4', [5, 6]]
<class 'numpy.ndarray'> [[1 2]
 [3 4]]


In [36]:
# ndarray는 벡터(Vector)와 행렬(Matrix)
# 1) list의 연산(배수)
data = [0,1,2,3,4,5,6,7,8,9] # 각 요소를 2배를 할 경우
result = data * 2 
print(type(result), result)  # list인 data를 2 times

# list자료를 벡터화같은 연산을 할경우
result = []
for d in data:
    result.append(d * 2)
print(type(result), result)
    
# 2) 벡터화연산
# 비교연산, 논리연산을 포함한 모든 종류의 수학 연산을 할 수가 있다.
# 이 의미는 선형대수에 적용되는 연산(행렬연산)이 가능하다
arr5 = np.array(data)  # 벡터의 연산
result = arr5 * 2
print(type(result), result)
print()

# a. 비교연산
result = arr5 == 2   # if arr5[i] == 2
print(type(result), result)
result = arr5%2 == 0         # if arr5[i]%2 == 0
print(type(result), result)
print()

a = np.array([1,2,3])
b = np.array([10,20,30])

print(a ==2)
print(b > 10)
print()

print((a==2) & (b>10))

<class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'> [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
<class 'numpy.ndarray'> [ 0  2  4  6  8 10 12 14 16 18]

<class 'numpy.ndarray'> [False False  True False False False False False False False]
<class 'numpy.ndarray'> [ True False  True False  True False  True False  True False]

[False  True False]
[False  True  True]

[False  True False]


In [ ]:
# 2차원 배열 만들기, 2x3의 2차원배열 생성하기
arr6 = np.array([[0,1,2],[3,4,5]])
print(type(arr6), arr6)

# arr7 = np.array([[0,1,2],[3,4,5,6]]) # inhomogeneous에러 즉 차원, 요소의 갯수가 다를 경우, 에러발생

In [42]:
# 2차원배열의 행과 열의 갯수구하기
print(len(arr6))    # 행의 갯수
print(len(arr6[0])) # 첫 번째행의 열의 갯수

2
3


In [47]:
# 3차원배열 만들기 2x3x4
list3 = [[[1,2,3,4], [5,6,7,8], [9,10,11,12]],           # 1면, 3행, 4열
        [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]     # 2면, 3행, 4열 
print(type(list3), list3)   

arr7 = np.array(list3)
print(type(arr7), arr7)

<class 'list'> [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
<class 'numpy.ndarray'> [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [57]:
# 배열의 차원과 크기 알아내기
print(f'배열의 차원 = {arr7.ndim} 차원')
print(f'배열의 크기 = {arr7.shape} 크기(형태)')

배열의 차원 = 3 차원
배열의 크기 = (2, 3, 4) 크기(형태)


##### 2. numpy 배열의 indexing과 slicing

In [72]:
# 1. indexing : 대괄호[인덱스]로 접근
# 양수, 음수로 접근할 수 있는데 음수는 뒤에서 부터 인덱싱을 한다.

# 1) 1차원일 경우
# 배열명[인덱스]
a = np.array([0,1,2,3,4])
print(a[0],a[1],a[2],a[3],a[4])

# 2) 2차원일 경우
# 배열명[행,열]
a = np.array([[0,1,2],[3,4,5]])
print(f'1st행={a[0,]}, 2nd행={a[1,]}')
print()

print(f'1st행={a[0,]}, 1st행의 1st열={a[0,0]}')
print(f'1st행={a[0,]}, 1st행의 2nd열={a[0,1]}')
print(f'1st행={a[0,]}, 1st행의 3rd열={a[0,2]}')
print()

print(f'2nd행={a[1,]}, 2nd행의 1st열={a[1,0]}')
print(f'2nd행={a[1,]}, 2nd행의 2nd열={a[1,1]}')
print(f'2nd행={a[1,]}, 2nd행의 3rd열={a[1,2]}')
print()

#0 3) 음수로 인덱싱할 경우 - 뒤에서부터 접근
print(a[-1,-1] , '=', a[1,2]) 
print(a[-1,-2] , '=', a[1,1])
print(a[-1,-3] , '=', a[1,0]) 

0 1 2 3 4
1st행=[0 1 2], 2nd행=[3 4 5]

1st행=[0 1 2], 1st행의 1st열=0
1st행=[0 1 2], 1st행의 2nd열=1
1st행=[0 1 2], 1st행의 3rd열=2

2nd행=[3 4 5], 2nd행의 1st열=3
2nd행=[3 4 5], 2nd행의 2nd열=4
2nd행=[3 4 5], 2nd행의 3rd열=5

5 = 5
4 = 4
3 = 3


In [92]:
# 2. slicing : 대괄호[:,:] -> 슬라이싱은 :으로 구분 [:(행), :(열)]
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a, a.ndim, a.shape)
print()

print(f'1st행의 열의 전체 = {a[0,:]}')
print(f'2nd행의 열의 전체 = {a[1,:]}')
print()

print(f'1st열의 행의 전체 = {a[:,0]}')
print(f'2nd열의 행의 전체 = {a[:,1]}')
print(f'3rd열의 행의 전체 = {a[:,2]}')
print(f'4th열의 행의 전체 = {a[:,3]}')
print()

print(f'2nd행의 1st열 = {a[1,0:1]}') # [start:end-1, strat:end-1]
print(f'2nd행의 1st~2nd열 = {a[1,0:2]}')
print()

print(f'전체행의 전체열(1) = {a[:,:]}') # 콜론 전후로 지정값이 없을 경우 전은 맨앞, 후는 맨뒤의미
print(f'전체행의 전체열(2) = {a[:,]}')
print(f'전체행의 전체열(3) = {a[0:2,]}')
print(f'전체행의 전체열(4) = {a[0:-1,]}')
print()

print(f'마지막행의 마지막열(1) = {a[1:,3:]}')
print(f'마지막행의 마지막열(2) = {a[-1:,-1:]}')

[[0 1 2 3]
 [4 5 6 7]] 2 (2, 4)

1st행의 열의 전체 = [0 1 2 3]
2nd행의 열의 전체 = [4 5 6 7]

1st열의 행의 전체 = [0 4]
2nd열의 행의 전체 = [1 5]
3rd열의 행의 전체 = [2 6]
4th열의 행의 전체 = [3 7]

2nd행의 1st열 = [4]
2nd행의 1st~2nd열 = [4 5]

전체행의 전체열(1) = [[0 1 2 3]
 [4 5 6 7]]
전체행의 전체열(2) = [[0 1 2 3]
 [4 5 6 7]]
전체행의 전체열(3) = [[0 1 2 3]
 [4 5 6 7]]
전체행의 전체열(4) = [[0 1 2 3]]

마지막행의 마지막열(1) = [[7]]
마지막행의 마지막열(2) = [[7]]


In [98]:
# 슬라이싱의 step [start:end-1:step, start:end-1:step]
a = np.array([[0,1,2,3],[4,5,6,7], [8,9,10,11]])
print(f'전체행중 2행씩 건너서 전체열 = {a[::2,:]}')
print(f'전체행중 1행씩 건너서 전체열 = {a[:,:]}')
print()

#  [[0,1,2,3], [8,9,10,11]] -> [[0,2], [8,10]]
print(f'전체행중 2행씩 건너서 전체열중 2열씩 건너서 = {a[::2,::2]}')

전체행중 2행씩 건너서 전체열 = [[ 0  1  2  3]
 [ 8  9 10 11]]
전체행중 1행씩 건너서 전체열 = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

전체행중 2행씩 건너서 전체열중 2열씩 건너서 = [[ 0  2]
 [ 8 10]]


##### 3. fancy indexing(배열인덱싱)

* 인덱싱이란 이름이 부여됬지만 실제는 db의 query의 기능을 수행한다.
* `불리언배열과, 정수배열`방식 2가지가 있다.
   - 블리언인덱싱방식은 배열의 `원소가 True, False 2개의 값으로만 구성`되면 원ndarray와 크기가 동일해야 한다.
   - 정수형 인덱싱은 인덱스가 존재한다면 원ndarray와 크기가 달라도 상관없다.

In [105]:
# 1. boolean indexing
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False,True, False,True, False,True, False])
print(a.shape, idx.shape)
print(a[idx])

# 조건식
print(a % 2) # 나머지값
print(a[a%2])
print(a[a%2==0])



(10,) (10,)
[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1]
[0 2 4 6 8]


In [109]:
# 2. 정수 indexing - 직접 요소의 위치 즉, 인덱스를 지정하는 방법
# 
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([0,2,4,6,8])
print(a[idx])  

idx = np.array([0,0,0]) # 원 배열과 크기가 다르다.
print(a[idx])

idx = np.array([0,8,9])
print(a[idx])

idx = np.array([0,8,8,8,8,8,9,4,4,4,4,4,2,2,2,2])
print(a[idx])

[0 2 4 6 8]
[0 0 0]
[0 8 9]
[0 8 8 8 8 8 9 4 4 4 4 4 2 2 2 2]


In [110]:
# 3. 배열의 인덱싱은 다차원배열에도 적용할 수 있다.