1. numpy 배열
1. numpy 배열의 생성과 변형
1. numpy 배열의 연산
1. 기술통계
1. 난수발생과 카운팅

* `Numpy의 핵심은 ndarray이다.`
* `np.array()함수는 list, tuple, array로 부터 ndarrary객체를 생성`
* ndarray는 N-dimensional Array의 약자이다. 즉, `다차원(1,2,...N차원)배열 자료구조를 지원`한다.

In [1]:
import numpy as np

##### 1. numpy 배열

In [4]:
# 1. 1차원배열 만들기
# np.array()함수에 list자료형을 전달하면 ndarray 객체 즉, 배열로 리턴한다.
# ndarray는 list와 유산한 구조처럼보이지만 배열객체와 리스트객체는 많은 차이가 있다.
# 1. list에는 서로 다른 타입의 자료를 저장할 수 있지만 ndarray은 동일 타입의 자료만 저장이 가능
# 2. ndarray는 다차원배열의 수치자료를 연산할 수 있다.
arr1 = np.array([1,2,3,4,5])
print(type(arr1), arr1)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [12]:
# 데이터타입이 틀린경우 강제형변환이 가능하다. 
# 1) 수치자료형은 상위의 데이터타입으로 변환이 된다.
# 2) string 요소가 있을 경우에 수치타입은 전부 str타입으로 강제형변환된다.
arr1 = np.array([1.0, 2, 3, 1.0])  # int -> float
print(type(arr1), arr1)
print()

arr2 = np.array([1.0, 2, 3, '1.0']) # 각요소가 전부 string타입으로 강제형변환
print(type(arr2), arr2)
print(type(arr2[3]), arr2[3])

arr3 = np.array([1.0, 2, 3, '일'])
print(type(arr3), arr3)
print(type(arr3[3]), arr3[3])

<class 'numpy.ndarray'> [1. 2. 3. 1.]

<class 'numpy.ndarray'> ['1.0' '2' '3' '1.0']
<class 'numpy.str_'> 1.0
<class 'numpy.ndarray'> ['1.0' '2' '3' '일']
<class 'numpy.str_'> 일


In [23]:
# 비동차는 지원하지 않는다. 차원이 다를 경우 에러가 발생된다.
# 즉, ndarray의 요소의 차원수는 동일해야 한다.
# 동차(homogeneous), 비동차(inhomogeneous)
list1 = [1,2,3, '4', [5,6]]
print(type(list1), list1)
# arr4 = np.array(list1) # 비동차에러, inhomogeneous part

list2 = [[1,2], [3,4]] # 첫 번쨰 요소와 두 번째 요소 모두 동차(1차원), 
arr4 = np.array(list2)
print(type(arr4), arr4)

<class 'list'> [1, 2, 3, '4', [5, 6]]
<class 'numpy.ndarray'> [[1 2]
 [3 4]]


In [36]:
# ndarray는 벡터(Vector)와 행렬(Matrix)
# 1) list의 연산(배수)
data = [0,1,2,3,4,5,6,7,8,9] # 각 요소를 2배를 할 경우
result = data * 2 
print(type(result), result)  # list인 data를 2 times

# list자료를 벡터화같은 연산을 할경우
result = []
for d in data:
    result.append(d * 2)
print(type(result), result)
    
# 2) 벡터화연산
# 비교연산, 논리연산을 포함한 모든 종류의 수학 연산을 할 수가 있다.
# 이 의미는 선형대수에 적용되는 연산(행렬연산)이 가능하다
arr5 = np.array(data)  # 벡터의 연산
result = arr5 * 2
print(type(result), result)
print()

# a. 비교연산
result = arr5 == 2   # if arr5[i] == 2
print(type(result), result)
result = arr5%2 == 0         # if arr5[i]%2 == 0
print(type(result), result)
print()

a = np.array([1,2,3])
b = np.array([10,20,30])

print(a ==2)
print(b > 10)
print()

print((a==2) & (b>10))

<class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'> [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
<class 'numpy.ndarray'> [ 0  2  4  6  8 10 12 14 16 18]

<class 'numpy.ndarray'> [False False  True False False False False False False False]
<class 'numpy.ndarray'> [ True False  True False  True False  True False  True False]

[False  True False]
[False  True  True]

[False  True False]


In [ ]:
# 2차원 배열 만들기, 2x3의 2차원배열 생성하기
arr6 = np.array([[0,1,2],[3,4,5]])
print(type(arr6), arr6)

# arr7 = np.array([[0,1,2],[3,4,5,6]]) # inhomogeneous에러 즉 차원, 요소의 갯수가 다를 경우, 에러발생

In [42]:
# 2차원배열의 행과 열의 갯수구하기
print(len(arr6))    # 행의 갯수
print(len(arr6[0])) # 첫 번째행의 열의 갯수

2
3


In [47]:
# 3차원배열 만들기 2x3x4
list3 = [[[1,2,3,4], [5,6,7,8], [9,10,11,12]],           # 1면, 3행, 4열
        [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]     # 2면, 3행, 4열 
print(type(list3), list3)   

arr7 = np.array(list3)
print(type(arr7), arr7)

<class 'list'> [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
<class 'numpy.ndarray'> [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [57]:
# 배열의 차원과 크기 알아내기
print(f'배열의 차원 = {arr7.ndim} 차원')
print(f'배열의 크기 = {arr7.shape} 크기(형태)')

배열의 차원 = 3 차원
배열의 크기 = (2, 3, 4) 크기(형태)


##### 2. numpy 배열의 indexing과 slicing

In [72]:
# 1. indexing : 대괄호[인덱스]로 접근
# 양수, 음수로 접근할 수 있는데 음수는 뒤에서 부터 인덱싱을 한다.

# 1) 1차원일 경우
# 배열명[인덱스]
a = np.array([0,1,2,3,4])
print(a[0],a[1],a[2],a[3],a[4])

# 2) 2차원일 경우
# 배열명[행,열]
a = np.array([[0,1,2],[3,4,5]])
print(f'1st행={a[0,]}, 2nd행={a[1,]}')
print()

print(f'1st행={a[0,]}, 1st행의 1st열={a[0,0]}')
print(f'1st행={a[0,]}, 1st행의 2nd열={a[0,1]}')
print(f'1st행={a[0,]}, 1st행의 3rd열={a[0,2]}')
print()

print(f'2nd행={a[1,]}, 2nd행의 1st열={a[1,0]}')
print(f'2nd행={a[1,]}, 2nd행의 2nd열={a[1,1]}')
print(f'2nd행={a[1,]}, 2nd행의 3rd열={a[1,2]}')
print()

#0 3) 음수로 인덱싱할 경우 - 뒤에서부터 접근
print(a[-1,-1] , '=', a[1,2]) 
print(a[-1,-2] , '=', a[1,1])
print(a[-1,-3] , '=', a[1,0]) 

0 1 2 3 4
1st행=[0 1 2], 2nd행=[3 4 5]

1st행=[0 1 2], 1st행의 1st열=0
1st행=[0 1 2], 1st행의 2nd열=1
1st행=[0 1 2], 1st행의 3rd열=2

2nd행=[3 4 5], 2nd행의 1st열=3
2nd행=[3 4 5], 2nd행의 2nd열=4
2nd행=[3 4 5], 2nd행의 3rd열=5

5 = 5
4 = 4
3 = 3


In [92]:
# 2. slicing : 대괄호[:,:] -> 슬라이싱은 :으로 구분 [:(행), :(열)]
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a, a.ndim, a.shape)
print()

print(f'1st행의 열의 전체 = {a[0,:]}')
print(f'2nd행의 열의 전체 = {a[1,:]}')
print()

print(f'1st열의 행의 전체 = {a[:,0]}')
print(f'2nd열의 행의 전체 = {a[:,1]}')
print(f'3rd열의 행의 전체 = {a[:,2]}')
print(f'4th열의 행의 전체 = {a[:,3]}')
print()

print(f'2nd행의 1st열 = {a[1,0:1]}') # [start:end-1, strat:end-1]
print(f'2nd행의 1st~2nd열 = {a[1,0:2]}')
print()

print(f'전체행의 전체열(1) = {a[:,:]}') # 콜론 전후로 지정값이 없을 경우 전은 맨앞, 후는 맨뒤의미
print(f'전체행의 전체열(2) = {a[:,]}')
print(f'전체행의 전체열(3) = {a[0:2,]}')
print(f'전체행의 전체열(4) = {a[0:-1,]}')
print()

print(f'마지막행의 마지막열(1) = {a[1:,3:]}')
print(f'마지막행의 마지막열(2) = {a[-1:,-1:]}')

[[0 1 2 3]
 [4 5 6 7]] 2 (2, 4)

1st행의 열의 전체 = [0 1 2 3]
2nd행의 열의 전체 = [4 5 6 7]

1st열의 행의 전체 = [0 4]
2nd열의 행의 전체 = [1 5]
3rd열의 행의 전체 = [2 6]
4th열의 행의 전체 = [3 7]

2nd행의 1st열 = [4]
2nd행의 1st~2nd열 = [4 5]

전체행의 전체열(1) = [[0 1 2 3]
 [4 5 6 7]]
전체행의 전체열(2) = [[0 1 2 3]
 [4 5 6 7]]
전체행의 전체열(3) = [[0 1 2 3]
 [4 5 6 7]]
전체행의 전체열(4) = [[0 1 2 3]]

마지막행의 마지막열(1) = [[7]]
마지막행의 마지막열(2) = [[7]]


In [98]:
# 슬라이싱의 step [start:end-1:step, start:end-1:step]
a = np.array([[0,1,2,3],[4,5,6,7], [8,9,10,11]])
print(f'전체행중 2행씩 건너서 전체열 = {a[::2,:]}')
print(f'전체행중 1행씩 건너서 전체열 = {a[:,:]}')
print()

#  [[0,1,2,3], [8,9,10,11]] -> [[0,2], [8,10]]
print(f'전체행중 2행씩 건너서 전체열중 2열씩 건너서 = {a[::2,::2]}')

전체행중 2행씩 건너서 전체열 = [[ 0  1  2  3]
 [ 8  9 10 11]]
전체행중 1행씩 건너서 전체열 = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

전체행중 2행씩 건너서 전체열중 2열씩 건너서 = [[ 0  2]
 [ 8 10]]


##### 3. fancy indexing(배열인덱싱)

* 인덱싱이란 이름이 부여됬지만 실제는 db의 query의 기능을 수행한다.
* `불리언배열과, 정수배열`방식 2가지가 있다.
   - 블리언인덱싱방식은 배열의 `원소가 True, False 2개의 값으로만 구성`되면 원ndarray와 크기가 동일해야 한다.
   - 정수형 인덱싱은 인덱스가 존재한다면 원ndarray와 크기가 달라도 상관없다.

In [105]:
# 1. boolean indexing
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False,True, False,True, False,True, False])
print(a.shape, idx.shape)
print(a[idx])

# 조건식
print(a % 2) # 나머지값
print(a[a%2])
print(a[a%2==0])



(10,) (10,)
[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1]
[0 2 4 6 8]


In [109]:
# 2. 정수 indexing - 직접 요소의 위치 즉, 인덱스를 지정하는 방법
# 
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([0,2,4,6,8])
print(a[idx])  

idx = np.array([0,0,0]) # 원 배열과 크기가 다르다.
print(a[idx])

idx = np.array([0,8,9])
print(a[idx])

idx = np.array([0,8,8,8,8,8,9,4,4,4,4,4,2,2,2,2])
print(a[idx])

[0 2 4 6 8]
[0 0 0]
[0 8 9]
[0 8 8 8 8 8 9 4 4 4 4 4 2 2 2 2]


In [11]:
#### 3. 배열의 인덱싱은 다차원배열에도 적용할 수 있다.
import numpy as np

m = np.array([[[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]]])
print(f'배열의 크기 = {m.shape}')

# 1. 3차원의 인덱싱
print(f'맨 처음 요소 = {m[0][0][0]}')
print(f'맨 2nd 요소 = {m[0][0][1]}')
print()

# 2. 3차원의 슬라이싱
print(m[:][:][:])
print(m[:][:][:,-1])

배열의 크기 = (1, 3, 5)
맨 처음 요소 = 0
맨 2nd 요소 = 1

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
[[10 11 12 13 14]]


##### 4. 배열의 생성과 변형

* 넘파이자료형 : ndarray의 요소는 모두 동일 자료형이어야 한다.
* 명시적으로 데이터타입을 정의하려면 dtype인수를 사용해야 한다.
* dtype를 정의하지 않았다면 python엔진이 자료형을 유추해서 결정한다.

In [13]:
# ndarray의 데이터타입속성
x = np.array([1,2,3])
print(x.dtype)

x = np.array([1.0,2,3])
print(x.dtype)

dtype('float64')

* dtype인수로 지정할 자료형 `dtype 접두사`로 시작하는 문자열, 뒤에 숫자는 바이트수의미
|dtype 접두사|설명|사용예|
|:---:|:-------------|:-----------|
|b|블리언|b(True or False)|
|i|정수|i8(64bit)|
|u|부호가 없는 정수|u8(64비트)|
|f|부동소수점|f32(256비트)|
|c|복소수|c16(128비트)|
|o|객체|o(객체에 대한 메모리주소)|
|s|바이트문자열|s24(24글자)|
|U|유니코드문자열|U24(24유니코드글자)|


In [19]:
x = np.array([1,2,3], dtype='f')
print(x.dtype, x[0].dtype, x[0]+x[1])

x = np.array([1,2,3], dtype='U')
print(x.dtype, x[0].dtype, x[0]+x[1])

float32 float32 3.0
<U1 <U1 12


In [ ]:
# Inf와 NaN
# np.inf(infinity) : 정의할 수 없는 숫자
# np.nan(Not a Number) : 수치가 아닌 값

#### 4. 배열생성함수

* zeros, ones
* zeros_like, ones_like
* empty
* arange
* linspace, logspace

In [27]:
# 1. zeros
a = np.zeros(5)
print(a)

a = np.zeros((2,3))
print(a, '\n')

# dtype을 설정할 수 있다.
a = np.zeros((2,3), dtype=np.int32)
print(a, '\n')

a = np.zeros((2,3), dtype='f')
print(a, '\n')

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]] 

[[0 0 0]
 [0 0 0]] 

[[0. 0. 0.]
 [0. 0. 0.]] 



In [30]:
# 2. ones
a = np.ones(5)
print(a, '\n')

a = np.ones([2,3])
print(a, '\n')

a = np.ones((2,3,5), dtype='i8')
print(a, '\n')

[1. 1. 1. 1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]] 



In [35]:
# zeros_like, ones_like
x = np.ones([2,3])
y = np.zeros_like(x, dtype='i')
print(y, '\n')

x = np.zeros([2,3])
y = np.ones_like(x, dtype='i')
print(y, '\n')

[[0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]] 



In [39]:
# empty
# 배열의 크기가 커지면 배열을 초기화하는데도 시간이 많이 걸린다.
# 이 시간을 단축하려면 배열만 생성하고 특정한 값으로 초기화하지 않는 함수
%reset -f
import numpy as np

e = np.empty((4,3))
e

array([[1.39192964e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.78020168e-306, 2.61254673e-057],
       [8.44777789e+169, 7.31391982e-042, 1.20990385e+161],
       [7.19439966e-067, 1.36967665e-071, 3.12391854e-033]])

In [42]:
# arrange(start, end-1, step)
np.arange(10) # 0~9
np.arange(10, 20) # 10~19
np.arange(10, 20, 2) # 10, 12, 14, 16, 18

array([10, 12, 14, 16, 18])

In [48]:
# linspace(start, end-1, size) : 선형구간을 지정한 구간의 수만큼 분할하는 함수
print(np.linspace(0, 100, 5))
print(np.logspace(0, 100, 5))

[  0.  25.  50.  75. 100.]
[1.e+000 1.e+025 1.e+050 1.e+075 1.e+100]


In [52]:
# 배열의 전치(pivot)
# 2차원 배열의 전치(transpose)연산은 행과 열을 바꾸는 작업
# T는 메서드가 아닌, 배열의 속성
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


#### 5. 배열의 크기변형

* reshape : 배열내부데이터는 보존한 채로 형태만 변환하는 함수
* 예를 들어 12개원요소를 갖는 1차원행렬은 3x4형태의 2차원행렬을 만들 수가 있다.

In [67]:
# reshape할 때는 원소의 갯수가 일치해야 한다.
a = np.arange(12)
print(a.shape)

a = a.reshape(3,4)
print(a.shape)

a = a.reshape(3, -1)
print(a.shape)

a = a.reshape(2,3,2)
print(a.shape)

(12,)
(3, 4)
(3, 4)
(2, 3, 2)


In [73]:
# 다차원배열을 무조건 1차원배열로 변환, flatten(), ravel()
# flatten, ravel : 실행결과만 리턴, 원본자료는 변경되지 않는다.
# numpy.ravel()과의 차이점?
#   (1) flatten은 메모리를 차지하기 때문에 ravel보다 느리다.
#   (2) ravel()은 일차원으로 바뀐 뷰를 리턴하고, flatten()은 일차원으로 바뀐 복사본을 리턴한다.
a = a.flatten()
print(a.shape)

a = a.reshape(2,3,2) 
print(a.shape)

a = a.ravel() 
print(a.shape)

(12,)
(2, 3, 2)
(12,)


#### 6. 배열의 연결

* hstack, vstack, dstack, stack, r_, c_, tile

In [78]:
# 1. hstack : 행의 수가 같은 2개이상의 배열을 옆으로 연결
# 전제조건 : 하나의 list로 저장해야 한다.
a1 = np.ones((2,3))
a2 = np.zeros((2,2))
print(a1, '\n', a2)

np.hstack([a1,a2])

[[1. 1. 1.]
 [1. 1. 1.]] 
 [[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [82]:
# 2. vstack : 열의 수가 같은 2개이상의 배열을 위아래로 연결 즉, 행의 수가 증가
# 연결할 배열은 list로 저장해야 한다.
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
print(b1, '\n'*2, b2)
print()
print(np.vstack([b1, b2]))

[[1. 1. 1.]
 [1. 1. 1.]] 

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
# 3. dstack : 3차원 즉, 행이나 열이 아닌 깊이방향으로 합친다
# 원소의 차원이 증가
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
print(c1, '\n'*2, c2)
print()

cx = np.dstack([c1, c2])
print(cx)
print(cx.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)


In [88]:
# 4. stack : dstack의 기능을 확장한 것으로 마지막차원으로 연결하는 것이 아니라
# 사용자가 지정한 차원(축)으로 연결, axis(기본값 0)사용하여 연결후 회전방향을 결정
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
print(c1, '\n'*2, c2)
print()

# 1) axis=0
cx = np.stack([c1, c2])
print(cx)
print(cx.shape)
print()

# axis=1
cx = np.stack([c1, c2], axis=1)
print(cx)
print(cx.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)

[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]
(3, 2, 4)


In [89]:
# 5. r_ : hstack과 유사하지만 좌우로 연결, 
# 메서드임에도 소괄호를 사용하지 않고 대괄호를 사용한다.
np.r_[np.array([1,2,3]), np.array([4,5,6])] # 결과 1차원

array([1, 2, 3, 4, 5, 6])

In [90]:
# 6. c_ : 배열의 차원을 증가후 좌우로 연결 즉, 1차원인 경우 2차원으로 변경
np.c_[np.array([1,2,3]), np.array([4,5,6])] # 결과 2차원

array([[1, 4],
       [2, 5],
       [3, 6]])

In [93]:
# 7. tile : 동일한 배열을 반복
a = np.array([[0,1,2], [3,4,5]])
print(np.tile(a, 2))
print()

print(np.tile(a, (3,2)))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [97]:
# 8. meshgrid명령 : 2차원함수의 쌍 즉, 그리드 포인트를 생성
# 사각형영역안의 그리드 포인트를 생성
x1 = np.arange(3)
x1
x2 = np.arange(5)
x2

X, y = np.meshgrid(x1, x2)
print(X, y)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [99]:
[list(zip(X, y)) for X, y in zip(X, y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

#### 배열의 연산

In [105]:
# z = x + y
x = np.arange(1, 1000001)
y = np.arange(1000001, 2000001)

z = np.zeros_like(x)

%time
for i in range(1000000):
    z[i] = x[i] + y[i]
    
print()

CPU times: total: 0 ns
Wall time: 0 ns



In [110]:
# 선형대수의 행렬연산(4칙연산) - 속도가 빠르다.
%time
z = x + y
z[:5]

CPU times: total: 0 ns
Wall time: 0 ns


array([9.999990e-07, 1.999996e-06, 2.999991e-06, 3.999984e-06,
       4.999975e-06])

In [115]:
# 선형대수 논리연산
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])
print(a == b)
print(a >= b)
print(a <= b)

# 배열의 각요소를 하나씩 비교하는 것이 아니라 모든가 다 같은지 여부
print(np.all(a == b))
print(np.all(a == c))

[False  True False  True]
[False  True  True  True]
[ True  True False  True]
False
True


In [120]:
# 스칼라와 벡터/행렬의 곱셈 (행렬연산)
x = np.arange(10)
x
print(x * 10)

x = np.arange(12).reshape(3,4)
x
print(x * 100)

[ 0 10 20 30 40 50 60 70 80 90]
[[   0  100  200  300]
 [ 400  500  600  700]
 [ 800  900 1000 1100]]


In [126]:
# 브로드캐스팅 : 행렬의 차원크기가 다를 경우 행렬을 확장하는 개념
x = np.arange(5)
y = 5
print(x.shape)
print
print(x + y)

(5,)
[5 6 7 8 9]


##### 차원축소연산

* min, max, argmin, argmax
* sum, mean, median, std, var
* all, any : 블리언

In [135]:
x = np.array([1,2,3,4])
print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.argmin(x))
print(np.argmax(x))
print(np.median(x))
print(np.mean(x))

print(np.all([True, True, False]))
print(np.any([True, True, False]))

10
1
4
0
3
2.5
2.5
False
True


In [140]:
# 정렬 : sort함수나 메서드를 사용하여 배열안의 원소크기를 정렬하여 새로운 배열을 생성
# axis=0, axis=1
# sort는 자체변화함수 즉 inplace=True
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a
print(np.sort(a)) # axis=1 행
print(np.sort(a, axis=0)) # axis=0 열

# 자료가 변형되는 것이 아니라 순서만 알고 싶을 경우는 argsort명령을 사용
# 정렬된 순서를 리턴
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
np.argsort(a)

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]


array([[1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)

In [ ]:
print